CREATE DATABASE IF NOT EXISTS `blog` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `blog`;

-- 导出  表 xrtask.TTASK_USER 结构
CREATE TABLE IF NOT EXISTS `tblog_user` (
  `OPER_NO` int(11) NOT NULL AUTO_INCREMENT,
  `OPER_TYPE` varchar(10) DEFAULT NULL,
  `OPER_USER_NAME` varchar(20) DEFAULT NULL,
  `OPER_PASSWORD` varchar(20) DEFAULT NULL,
  `OPER_BRANCH_ID` int(11) DEFAULT NULL,
  `OPER_REAL_NAME` varchar(20) DEFAULT NULL,
  `OPER_PHONE` varchar(15) DEFAULT NULL,
  `OPER_EMAIL` varchar(50) DEFAULT NULL,
  `OPER_ID_NO` varchar(20) DEFAULT NULL,
  `OPER_ROLE` varchar(10) DEFAULT NULL,
  `OPER_STATUS` varchar(10) DEFAULT NULL,
  `OPER_START_DATE` date DEFAULT NULL,
  `OPER_END_DATE` date DEFAULT NULL,
  PRIMARY KEY (`OPER_NO`)
) ENGINE=InnoDB AUTO_INCREMENT=10001 DEFAULT CHARSET=utf8;
